changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - "feature*"
        - "feat*"
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - "fix*"
    - title: "📚 Documentation"
      labels:
        - documentation
        - "docs*"
    - title: "🛠 Maintenance & Refactoring"
      labels:
        - chore
        - "chore*"
        - "refactor*"
        - "perf*"
    - title: "🧰 Other Changes"
      labels:
        - "*"

