/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertsEvents: typeof import('./src/components/dashboard/AlertsEvents.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfigDataTable: typeof import('./src/components/config/ConfigDataTable.vue')['default']
    ConfigDetailsDrawer: typeof import('./src/components/config/ConfigDetailsDrawer.vue')['default']
    ConfigMetricsCards: typeof import('./src/components/config/ConfigMetricsCards.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    HealthOverview: typeof import('./src/components/dashboard/HealthOverview.vue')['default']
    NodeMetricsCards: typeof import('./src/components/nodes/NodeMetricsCards.vue')['default']
    NodesTable: typeof import('./src/components/nodes/NodesTable.vue')['default']
    PodDetailsDrawer: typeof import('./src/components/pods/PodDetailsDrawer.vue')['default']
    PodMetricsCards: typeof import('./src/components/pods/PodMetricsCards.vue')['default']
    PodsDataTable: typeof import('./src/components/pods/PodsDataTable.vue')['default']
    ResourceUsage: typeof import('./src/components/dashboard/ResourceUsage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceDetailsDrawer: typeof import('./src/components/services/ServiceDetailsDrawer.vue')['default']
    ServiceMetricsCards: typeof import('./src/components/services/ServiceMetricsCards.vue')['default']
    ServicesDataTable: typeof import('./src/components/services/ServicesDataTable.vue')['default']
    StatusSummary: typeof import('./src/components/dashboard/StatusSummary.vue')['default']
    StorageClassesSidebar: typeof import('./src/components/storage/StorageClassesSidebar.vue')['default']
    StorageMetricsCards: typeof import('./src/components/storage/StorageMetricsCards.vue')['default']
    StorageOverview: typeof import('./src/components/storage/StorageOverview.vue')['default']
    StoragePVCTable: typeof import('./src/components/storage/StoragePVCTable.vue')['default']
    StoragePVTable: typeof import('./src/components/storage/StoragePVTable.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TopConsumers: typeof import('./src/components/dashboard/TopConsumers.vue')['default']
    WorkloadDetailsDrawer: typeof import('./src/components/workloads/WorkloadDetailsDrawer.vue')['default']
    WorkloadMetricsCards: typeof import('./src/components/workloads/WorkloadMetricsCards.vue')['default']
    WorkloadsDataTable: typeof import('./src/components/workloads/WorkloadsDataTable.vue')['default']
    WorkloadsTable: typeof import('./src/components/nodes/WorkloadsTable.vue')['default']
    WorkloadSummaries: typeof import('./src/components/dashboard/WorkloadSummaries.vue')['default']
  }
}
