/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertsEvents: typeof import('./src/components/dashboard/AlertsEvents.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfigDataTable: typeof import('./src/components/config/ConfigDataTable.vue')['default']
    ConfigDetailsDrawer: typeof import('./src/components/config/ConfigDetailsDrawer.vue')['default']
    ConfigMetricsCards: typeof import('./src/components/config/ConfigMetricsCards.vue')['default']
    CronJobsTable: typeof import('./src/components/workloads/CronJobsTable.vue')['default']
    DaemonSetsTable: typeof import('./src/components/workloads/DaemonSetsTable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeploymentsTable: typeof import('./src/components/workloads/DeploymentsTable.vue')['default']
    EventDetailsDrawer: typeof import('./src/components/events/EventDetailsDrawer.vue')['default']
    EventMetricsCards: typeof import('./src/components/events/EventMetricsCards.vue')['default']
    EventsDataTable: typeof import('./src/components/events/EventsDataTable.vue')['default']
    GeneralSettingsForm: typeof import('./src/components/settings/GeneralSettingsForm.vue')['default']
    HealthOverview: typeof import('./src/components/dashboard/HealthOverview.vue')['default']
    JobsTable: typeof import('./src/components/workloads/JobsTable.vue')['default']
    NamespaceDetailsDrawer: typeof import('./src/components/namespaces/NamespaceDetailsDrawer.vue')['default']
    NamespaceMetricsCards: typeof import('./src/components/namespaces/NamespaceMetricsCards.vue')['default']
    NamespacesDataTable: typeof import('./src/components/namespaces/NamespacesDataTable.vue')['default']
    NodeMetricsCards: typeof import('./src/components/nodes/NodeMetricsCards.vue')['default']
    NodesTable: typeof import('./src/components/nodes/NodesTable.vue')['default']
    PodDetailsDrawer: typeof import('./src/components/pods/PodDetailsDrawer.vue')['default']
    PodMetricsCards: typeof import('./src/components/pods/PodMetricsCards.vue')['default']
    PodsDataTable: typeof import('./src/components/pods/PodsDataTable.vue')['default']
    PoliciesDataTable: typeof import('./src/components/policies/PoliciesDataTable.vue')['default']
    PoliciesMetricsCards: typeof import('./src/components/policies/PoliciesMetricsCards.vue')['default']
    PolicyDetailsDrawer: typeof import('./src/components/policies/PolicyDetailsDrawer.vue')['default']
    ReplicaSetsTable: typeof import('./src/components/workloads/ReplicaSetsTable.vue')['default']
    ResourceUsage: typeof import('./src/components/dashboard/ResourceUsage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceDetailsDrawer: typeof import('./src/components/services/ServiceDetailsDrawer.vue')['default']
    ServiceMetricsCards: typeof import('./src/components/services/ServiceMetricsCards.vue')['default']
    ServicesDataTable: typeof import('./src/components/services/ServicesDataTable.vue')['default']
    SettingsAboutTab: typeof import('./src/components/settings/SettingsAboutTab.vue')['default']
    SettingsGeneralTab: typeof import('./src/components/settings/SettingsGeneralTab.vue')['default']
    SettingsInfoCards: typeof import('./src/components/settings/SettingsInfoCards.vue')['default']
    StatefulSetsTable: typeof import('./src/components/workloads/StatefulSetsTable.vue')['default']
    StatusSummary: typeof import('./src/components/dashboard/StatusSummary.vue')['default']
    StorageClassesSidebar: typeof import('./src/components/storage/StorageClassesSidebar.vue')['default']
    StorageMetricsCards: typeof import('./src/components/storage/StorageMetricsCards.vue')['default']
    StorageOverview: typeof import('./src/components/storage/StorageOverview.vue')['default']
    StoragePVCTable: typeof import('./src/components/storage/StoragePVCTable.vue')['default']
    StoragePVTable: typeof import('./src/components/storage/StoragePVTable.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
    TopConsumers: typeof import('./src/components/dashboard/TopConsumers.vue')['default']
    UpdaterNotifications: typeof import('./src/components/UpdaterNotifications.vue')['default']
    WorkloadDetailsDrawer: typeof import('./src/components/workloads/WorkloadDetailsDrawer.vue')['default']
    WorkloadMetricsCards: typeof import('./src/components/workloads/WorkloadMetricsCards.vue')['default']
    WorkloadsTable: typeof import('./src/components/nodes/WorkloadsTable.vue')['default']
    WorkloadSummaries: typeof import('./src/components/dashboard/WorkloadSummaries.vue')['default']
  }
}
